### ISSUE TITLE
sprite.png is not transparent in the default theme

### ISSUE THREAD

**Issue by blackfriar** [pixelmatrix/uniform#407]
sprite.png is not transparent in the default theme while
the corresponding sprite.png is transparent in all other themes.
Why ??????
Could anybody explain this ?
I think lots of people need transparent sprite.png in the default theme.

**Comment by shehi** [comment]
https://github.com/pixelmatrix/uniform/blob/master/themes/default/images/sprite.png looks transparent to me. Am I missing something here?

**Comment by shehi** [comment]
Apparently the issue was fixed in v2.1.2.
