### ISSUE TITLE
add bower

### ISSUE THREAD

**Issue by gbelmm** [pixelmatrix/uniform#413]
register uniform en bower please

**Comment by P3trovichUA** [comment]
it would be great

**Comment by Arelav** [comment]
+1

**Comment by hacfi** [comment]
You can use `jquery.uniform` but we should work on a `bower.json` for better support.

**Comment by geordie--** [comment]
If you're interested I forked it to make a bowerized version: https://github.com/geordie--/uniform/releases/tag/2.1.3

**Comment by Mic75** [comment]
+1

**Comment by shehi** [comment]
Package is already accessible via Bower: ```bower info jquery.uniform```
